Zop-sys/Cooloc

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/layouts/application.html.erb

Installation de la gemme bootstrap sur gemfile

install gem bootstrap

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/home.html.erb

Component button.
Il reste la police à changer. En attente de la variable dans font.

button done

---

app/assets/stylesheets/components/_button.scss
app/views/pages/home.html.erb

 button finish

---

app/assets/stylesheets/components/_button.scss

correction d'un oublie de classe

 fix button

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

 Homepage done

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Boutons redesign sur les formulaires

Button form

---

app/views/pages/home.html.erb

Correction de la home page qui avait pété.

debug fix homepage

---

app/views/shared/_navbar.html.erb

Le logo de la navbar redirige vers la home

 Logo in navbar root to home

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_devise.scss
app/views/teams/new.html.erb

Mise en page de la page de création de la coloc faite. Le bouton est brute, il va changer avec le JS (add coloc)

Css in page create cooloc

---

app/assets/stylesheets/components/_images.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_input.scss
app/assets/stylesheets/components/_navbar.scss
app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/teams/new.html.erb

Flexbox sur les 2 img en haut de la home. J'ai corrigé le "bug" du container de App et ajusté les autres pages avec une marge sur les titres. 
Ajout également du current_user dans la droplist sur la navbar.

Flex homepage

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_images.scss
app/assets/stylesheets/pages/_home.scss

mediaqueries homepage

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_fonts.scss
app/views/shared/_navbar.html.erb

changement de la police dans la navbar et de la taille du texte (ainsi que dans la droplist)

Update police connection and  droplist

---

app/assets/stylesheets/components/_footer.scss

fix footer fixed

---

app/views/pages/home.html.erb

Redirection du bouton de la home selon le status de l'user

redirection button if current user is log or not

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/team_tasks/_form.html.erb

j'ai mis le titre au dessus du bouton.

remove title above button

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/layouts/application.html.erb
config/initializers/default_meta.rb
config/meta.yml

meta favicon facebook

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

debug droplist navbar

---

app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb

navbar :  transparence sur la navbar de la home page

fix navbar

---

app/assets/stylesheets/pages/_form.scss

 remove padding

---

db/seeds.rb

ajout de seed

---

app/assets/stylesheets/components/_footer.scss

height footer 45px au lieu de 50px

 less height footer

---

public/404.html

modification 404

---

app/assets/stylesheets/components/_cards.scss
app/views/team/teams/index.html.erb

create classement design in progress

---

app/views/team/teams/index.html.erb

debug classement
